### ISSUE TITLE
problem during runing run_kt.sh

### ISSUE THREAD

**Issue by cjjjy** [dspavankumar/keras-kaldi#15]
Hi, when i run the sh run_kt.sh ,it occur the problem as follows:
The path is
train=/kaldi-trunk/egs/timit/s5/data/train
test=/kaldi-trunk/egs/timit/s5/data/test
lang=/kaldi-trunk/egs/timit/s5/data/lang
gmm=/kaldi-trunk/egs/timit/s5/exp/tri2
exp=/kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr
Is my path set wrong that lead to the problem?

sudo sh run_kt.sh 
steps/align_si.sh --nj 4 --cmd  /kaldi-trunk/egs/timit/s5/data/train_cv05 /kaldi-trunk/egs/timit/s5/data/lang /kaldi-trunk/egs/timit/s5/exp/tri2 /kaldi-trunk/egs/timit/s5/exp/tri2_ali_cv05
steps/align_si.sh: empty argument to --cmd option
steps/align_si.sh --nj 4 --cmd  /kaldi-trunk/egs/timit/s5/data/train_tr95 /kaldi-trunk/egs/timit/s5/data/lang /kaldi-trunk/egs/timit/s5/exp/tri2 /kaldi-trunk/egs/timit/s5/exp/tri2_ali_tr95
steps/align_si.sh: empty argument to --cmd option
Using TensorFlow backend.
/usr/bin/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "steps_kt/train.py", line 57, in <module>
    compute_priors (exp, ali_tr, ali_cv)
  File "/kaldi-trunk/egs/aishell/s5/steps_kt/compute_priors.py", line 33, in compute_priors
    dim = read_output_feat_dim (exp)    
  File "/kaldi-trunk/egs/aishell/s5/steps_kt/compute_priors.py", line 26, in read_output_feat_dim
    p = Popen (['am-info', exp+'/final.mdl'], stdout=PIPE)
  File "/usr/bin/miniconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/bin/miniconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'am-info': 'am-info'
steps_kt/decode.sh --nj 4 --add-deltas true --norm-vars true --splice-opts --left-context=5 --right-context=5 /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps_kt/decode.sh: feature: splice(--left-context=5 --right-context=5) norm_vars(true) add_deltas(true)
steps_kt/decode.sh: line 84: JOB=1:4: command not found
+ steps/score_kaldi.sh --cmd '' /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/score_kaldi.sh --cmd  /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/score_kaldi.sh: empty argument to --cmd option

**Comment by dspavankumar** [comment]
> steps/align_si.sh --nj 4 --cmd /kaldi-trunk/egs/...

There is no argument to --cmd. You probably didn't run cmd.sh correctly.

> FileNotFoundError: [Errno 2] No such file or directory: 'am-info': 'am-info'

The Kaldi tools are not in path. Check your path.sh and run it correctly.

**Comment by cjjjy** [comment]
Thank you ,I check the path.sh and run the cmd.sh,and it worked. but antoher error produce during running run_kt.sh as follows:

sudo sh run_kt.sh

steps_kt/decode.sh --nj 4 --add-deltas true --norm-vars true --splice-opts --left-context=5 --right-context=5 /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps_kt/decode.sh: feature: splice(--left-context=5 --right-context=5) norm_vars(true) add_deltas(true)
bash: line 1: 47408 Aborted                 (core dumped) ( latgen-faster-mapped --max-active=7000 --beam=15.0 --lattice-beam=7.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=/kaldi-trunk/egs/timit/s5/exp/tri2/graph/words.txt /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/final.mdl /kaldi-trunk/egs/timit/s5/exp/tri2/graph/HCLG.fst "ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:/kaldi-trunk/egs/timit/s5/data/test/split4/4/utt2spk scp:/kaldi-trunk/egs/timit/s5/data/test/split4/4/cmvn.scp scp:/kaldi-trunk/egs/timit/s5/data/test/split4/4/feats.scp ark:- | splice-feats --left-context=5 --right-context=5 ark:- ark:- | add-deltas ark:- ark:- | python3 steps_kt/nnet-forward.py /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.nnet.h5 /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.priors.csv |" "ark:|gzip -c > /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/lat.4.gz" ) 2>> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.4.log >> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.4.log
bash: line 1: 47410 Aborted                 (core dumped) ( latgen-faster-mapped --max-active=7000 --beam=15.0 --lattice-beam=7.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=/kaldi-trunk/egs/timit/s5/exp/tri2/graph/words.txt /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/final.mdl /kaldi-trunk/egs/timit/s5/exp/tri2/graph/HCLG.fst "ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:/kaldi-trunk/egs/timit/s5/data/test/split4/1/utt2spk scp:/kaldi-trunk/egs/timit/s5/data/test/split4/1/cmvn.scp scp:/kaldi-trunk/egs/timit/s5/data/test/split4/1/feats.scp ark:- | splice-feats --left-context=5 --right-context=5 ark:- ark:- | add-deltas ark:- ark:- | python3 steps_kt/nnet-forward.py /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.nnet.h5 /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.priors.csv |" "ark:|gzip -c > /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/lat.1.gz" ) 2>> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.1.log >> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.1.log
bash: line 1: 47412 Aborted                 (core dumped) ( latgen-faster-mapped --max-active=7000 --beam=15.0 --lattice-beam=7.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=/kaldi-trunk/egs/timit/s5/exp/tri2/graph/words.txt /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/final.mdl /kaldi-trunk/egs/timit/s5/exp/tri2/graph/HCLG.fst "ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:/kaldi-trunk/egs/timit/s5/data/test/split4/2/utt2spk scp:/kaldi-trunk/egs/timit/s5/data/test/split4/2/cmvn.scp scp:/kaldi-trunk/egs/timit/s5/data/test/split4/2/feats.scp ark:- | splice-feats --left-context=5 --right-context=5 ark:- ark:- | add-deltas ark:- ark:- | python3 steps_kt/nnet-forward.py /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.nnet.h5 /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.priors.csv |" "ark:|gzip -c > /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/lat.2.gz" ) 2>> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.2.log >> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.2.log
bash: line 1: 47411 Aborted                 (core dumped) ( latgen-faster-mapped --max-active=7000 --beam=15.0 --lattice-beam=7.0 --acoustic-scale=0.1 --allow-partial=true --word-symbol-table=/kaldi-trunk/egs/timit/s5/exp/tri2/graph/words.txt /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/final.mdl /kaldi-trunk/egs/timit/s5/exp/tri2/graph/HCLG.fst "ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:/kaldi-trunk/egs/timit/s5/data/test/split4/3/utt2spk scp:/kaldi-trunk/egs/timit/s5/data/test/split4/3/cmvn.scp scp:/kaldi-trunk/egs/timit/s5/data/test/split4/3/feats.scp ark:- | splice-feats --left-context=5 --right-context=5 ark:- ark:- | add-deltas ark:- ark:- | python3 steps_kt/nnet-forward.py /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.nnet.h5 /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/dnn.priors.csv |" "ark:|gzip -c > /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/lat.3.gz" ) 2>> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.3.log >> /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.3.log
run.pl: 4 / 4 failed, log is in /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode/log/decode.*.log
+ steps/score_kaldi.sh --cmd 'run.pl --mem 10G' /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/score_kaldi.sh --cmd run.pl --mem 10G /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/score_kaldi.sh: scoring with word insertion penalty=0.0,0.5,1.0
+ steps/scoring/score_kaldi_cer.sh --stage 2 --cmd 'run.pl --mem 10G' /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/scoring/score_kaldi_cer.sh --stage 2 --cmd run.pl --mem 10G /kaldi-trunk/egs/timit/s5/data/test /kaldi-trunk/egs/timit/s5/exp/tri2/graph /kaldi-trunk/egs/timit/s5/exp/dnn4_pretrain-dbn_dnn_smbr/decode
steps/scoring/score_kaldi_cer.sh: scoring with word insertion penalty=0.0,0.5,1.0
+ echo 'local/score.sh: Done'
local/score.sh: Done
