### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by nirajvermafcb** [dspavankumar/keras-kaldi#3]
I am trying to run train.py and it is giving me the error:
    
 Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from dataGenerator import dataGenerator
  File "/home/niraj/projects/keras-kaldi-master/steps_kt/dataGenerator.py", line 20, in <module>
    from subprocess import Popen, PIPE, DEVNULL
ImportError: cannot import name DEVNULL

How to resolve this error?

**Comment by dspavankumar** [comment]
Are you using Python3.4+? Usually Python2 gives the error.

**Comment by nirajvermafcb** [comment]
I am using python 3.5
